# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: ./mysql.dockerfile
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306